name:                QR
version:             0.1.0.0
github:              "wvogel00/QR"
license:             BSD3
author:              "Wataru TORII"
maintainer:          "wtorii@hey.com"
copyright:           "2020 Wataru TORII here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wvogel00/QR#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- bits

library:
  source-dirs: src

executables:
  QR-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QR

tests:
  QR-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QR
